name: CI Build

on:
  push:
    branches: [ "main", "task4" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Speeds up future builds by caching dependencies

      - name: Install dependencies
        run: npm ci # 'ci' is faster and more reliable than 'install' for automated builds

      - name: Run Build
        run: npm run build # Vite's production build command

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-application
          path: dist/
          if-no-files-found: error
